// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231021160446_ProductSeeding")]
    partial class ProductSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Семён, смышлёный парнишка 22 лет, сидя в компании приятелей, ненароком заскучал. Развернув одну из старых газет, он обнаружил странное объявление: к некоему Магическому Двору приглашались желающие получить профессию мага-воина. Не подумав, Семён механически прочитал вслух заклинание под объявлением (причём слова «Магический Двор» он спьяну прочитал как «Магический Вор») и оказался на… Вселенском Диске рядом с Магическим вором – живым, говорящим медальоном на цепочке…",
                            ImageUrl = "https://avidreaders.ru/pics/3/8/64838.jpg",
                            Price = 9.99m,
                            Title = "Слимп"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Изумрудный Мир… Красивое название, не правда ли? А еще вот такие Миры: Тупиковый, Ханский, Мандариновый, Торговый, Выгребной… ну и Исправительный, как же без него? А еще Мир Равновесия, Мир Прокаженных и много всяких прочих. Все эти Истинные Миры располагаются на Вселенском Диске, по которому и скитается в поисках приключений или по необходимости удачливый вор Симеон, бывший «земной» студент, со своим странным другом – медальоном по имени Мар, обеспечивающим Симеону магическое прикрытие…",
                            ImageUrl = "https://avidreaders.ru/pics/0/3/433503.jpeg",
                            Price = 7.99m,
                            Title = "Слимпер"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Пока Семён, вор с магическим прикрытием, искал достойный подарок ко дню коронации Яны, правительницы одного из самых крупных королевств Изумрудного Мира, та внезапно решила выйти замуж за его друга и телохранителя Хайка, воина из клана Болотной Черепахи. Это повергло Семёна в некоторую растерянность, перешедшую в двухнедельный загул. Хорошо, что у него есть Мар, магический медальон, который вытаскивает его из нехороших ситуаций, перебрасывая из одного Мира в другой. Но все когда-нибудь надоедает. Вот и Семён решает наконец отдохнуть и хорошенько подумать, что делать дальше. И тут он получает заказ от главы Вседисковой Гильдии Воров, Мастера Четырех Углов, выкрасть магический жезл – якобы для его личной коллекции. Так Семён знакомится с внучкой этого Мастера – Олией. К ним неожиданно присоединяется Хайк. Приключения продолжаются…",
                            ImageUrl = "https://avidreaders.ru/pics/0/0/166100.jpg",
                            Price = 6.99m,
                            Title = "Слиперия"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
